### ISSUE TITLE
It's effed.

### ISSUE THREAD

**Issue by exys228** [exys228/osu-stuff#14]
Congrats! Now I have a full-time job and I don't think I will be able to do anything for this project in near future, even if I have the will. Tbh, thanks to ADHD I didn't do anything anyways. I hope my code is not that terrible for you guys and someone will eventually fork this and make something good out of it. The best thing I could do is to add documentation and README.md. Again, in near future. I'm sorry I am such a failure.

P.S. @xxCherry, my hopes on you!
P.P.S. I may suddenly come back, who knows me

**Comment by Hazuki-san** [comment]
Thank you for your project!
