### ISSUE TITLE
Need Help using de4dot

### ISSUE THREAD

**Issue by shinkuan** [exys228/osu-stuff#21]
I used de4dot to deobfuscate osu! (v3097)
It shows:
```Detected Eazfuscator.NET 5.2-5.8 (osu!v3097.exe)
Cleaning osu!v3097.exe
ERROR:
ERROR:
ERROR:
ERROR: Hmmmm... something didn't work. Try the latest version.
```

It is the latest version.

Thanks for the help, if any.

**Comment by shinkuan** [comment]
Tried v3095 and v3090, both of them don't work either.

**Comment by Hazuki-san** [comment]
Have you try clean.exe?

**Comment by shinkuan** [comment]
Thanks for the super fast response.
Not yet.
Should I clean the clean.exe? or it is already cleaned?

**Comment by Hazuki-san** [comment]
clean.exe is already cleaned and ready to use, you can find it in `osu!patch/etc/clean.exe`

**Comment by shinkuan** [comment]
Okay, what's my next step?
NameMapper?

**Comment by Hazuki-san** [comment]
NameMapper is used to clean another obfuscated osu!, you'll have to StringFixer the obfuscated client first then you can start NameMapping them.

**Comment by shinkuan** [comment]
So I StringFixer the obfuscated client and I started NameMapping them.

There are so many errors, is it normal to act like that?
![ERROR擷取](https://user-images.githubusercontent.com/35415788/92244303-4c234700-eef5-11ea-80da-8924008a1df9.PNG)

**Comment by Hazuki-san** [comment]
This is normal

**Comment by shinkuan** [comment]
What to do next?

**Comment by Hazuki-san** [comment]
Then you can start patching osu!

**Comment by shinkuan** [comment]
Sorry for another stupid question. How?
Which one should I use? osu!stuff, osu!patch, osu!patch.CLI
And how to use?

**Comment by Hazuki-san** [comment]
osu!patch.CLI, the executable will tell you how to use.

**Comment by shinkuan** [comment]
Thanks, you are really helpful!
